version: '3.8'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - M_WAITING_TIME=30000
      - CHROMIUM_PATH=/usr/bin/chromium-browser
      - AI_AGENT=FW
      - FW_ENDPOINT=http://localhost:3000/api/agents/herbakofAssistanceAgent/generate
      - JWT_SECRET=your-jwt-secret-key-here
      - RAILWAY_RUN_UID=0
      # Add your environment variables here
      # - WHITELISTED_NUMBERS=1234567890,9876543210
    volumes:
      - whatsapp_data:/data
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3003/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  whatsapp_data:
    driver: local
