services:
  app:
    build: .
    image: entrlab-wa  # Explicit image name, can be changed
    ports:
      - "3000:3000"  # Expose port 3000 from container to host
    volumes:
      - ./data/wwebjs_auth:/data/wwebjs_auth  # Use /data for persistent storage
      - ./data/wwebjs_cache:/data/wwebjs_cache  # Use /data for persistent storage
    env_file:
      - .env  # Load environment variables from a .env file
    environment:
      NODE_ENV: production  # Set additional environment variables
      CHROMIUM_PATH: /usr/bin/chromium  # Set Chromium path
    command: "node index.js"  # Command to run when the container starts
    restart: unless-stopped  # Automatically restart the container unless stopped manually
