[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/usr/src/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "whatsapp-bot"

# Volume configuration for session persistence
[[volumes]]
name = "whatsapp_data"
path = "/data"
